### ISSUE TITLE
Offer for writing WebBluetooth module and Documentation?

### ISSUE THREAD

**Issue by qdot** [kenkeiter/lantern#1]
Hey! First off, thanks for writing this library! I was about to order a couple of these on Amazon, saw people complaining about the app, and figured I'd see if anyone had reversed them, otherwise I was going to. So this project is already saving me time! :D

I'd love to contribute back. I do a lot of work reversing bluetooth/usb/etc devices, documenting protocols, etc. My work is at http://github.com/qdot / http://github.com/metafetish / http://github.com/openyou

Assuming you're not already in the middle of it, I can throw together some quick documentation for the protocol work you did, as well as a node.js/webbluetooth library, since Chrome on OS X/Linux/Android/ChromeOS should be able to control these lights directly. Just lemme know if that sounds good, don't want to step on work you may already be doing. :)

**Comment by kenkeiter** [comment]
I'm not working on that, currently, but I'd love to see that, if you're up for it 😄 

Glad to hear that this was of use to you! I'm a big fan of these lights.
