### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by ghost** [kenkeiter/lantern#3]
Hi, 
When I launch a program with this lib imported, it throws an error saying

`ImportError: cannot import name 'Light'` as called in the __init__.py of the lib.

Why so ? I can't figure this one out. 

Thanks !

**Comment by willtejeda** [comment]
You have to go into the modules init file and change the import name from Light to light 

seems like it's a capitalization error 

Hope this helps

**Comment by pesinasiller** [comment]
same problem, any update?
